FROM alpine:latest

### Twitter APIを呼び出すためにコンテナ内にCA証明書をインストール
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*

ARG SP_TWITTER_KEY
ARG SP_TWITTER_SECRET
ARG SP_TWITTER_ACCESSTOKEN
ARG SP_TWITTER_ACCESSSECRET
ARG MONGO_PASS

ENV SP_TWITTER_KEY=${SP_TWITTER_KEY} SP_TWITTER_SECRET=${SP_TWITTER_SECRET}
ENV SP_TWITTER_ACCESSTOKEN=${SP_TWITTER_ACCESSTOKEN} SP_TWITTER_ACCESSSECRET=${SP_TWITTER_ACCESSSECRET}
ENV MONGO_HOST=twitter-votes-mongodb MONGO_PORT=27017 MONGO_DB=ballots MONGO_USER=mongo MONGO_PASS=${MONGO_PASS} MONGO_SOURCE=ballots
ENV NSQ_HOST=twitter-votes-nsqd NSQ_PORT=4150 NSQ_TOPIC=votes

COPY twittervotes .

ENTRYPOINT ["./twittervotes"]